### ISSUE TITLE
Doesn't work on 1.20.2 with ViaBackwards

### ISSUE THREAD

**Issue by Mexican68** [pessiuff/PluginHide#1]
It works on 1.20.1 but not on my 1.20.2 paper server with ViaBackwards.

**Comment by pessiuff** [comment]
I'll test this and hopefully find a solution. Thanks for  informing.

**Comment by pessiuff** [comment]
![image](https://github.com/pessiuff/PluginHide/assets/85117021/8eff9fc0-60e2-458e-ac41-fef3286c0952)
I couldn't reproduce your problem with ViaBackwards. What is your ProtocolLib version?

**Comment by Mexican68** [comment]
I used the version you said to use in your mod description, the latest version of protocol lib. But both your plugin and protocol lib appear red in /plugins

**Comment by pessiuff** [comment]
Can you try [this](https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/artifact/build/libs/ProtocolLib.jar) version of ProtocolLib?

**Comment by Mexican68** [comment]
> Can you try [this](https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/artifact/build/libs/ProtocolLib.jar) version of ProtocolLib?

I tried this version and it worked, how'd it work tho? What version is that? What was wrong?

**Comment by pessiuff** [comment]
> > Can you try [this](https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/artifact/build/libs/ProtocolLib.jar) version of ProtocolLib?
> 
> I tried this version and it worked, how'd it work tho? What version is that? What was wrong?

Your ProtocolLib version was most likely old. Downloading ProtocolLib for 1.20.2 from https://ci.dmulloy2.net/job/ProtocolLib/ (ignore 5.1.1 for1.8-1.20.2) fixed your problem. 
![image](https://github.com/pessiuff/PluginHide/assets/85117021/f7a6b5e2-3832-41d6-9516-41808f80c7cc)
